// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLoT8km9AendlEHUHcqitr0qcewaL6qc',
    appId: '1:252455385930:web:94af412ba82b28b7069fb3',
    messagingSenderId: '252455385930',
    projectId: 'registration-7d627',
    authDomain: 'registration-7d627.firebaseapp.com',
    storageBucket: 'registration-7d627.firebasestorage.app',
    measurementId: 'G-8V65KYHV7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGbPtzx58ID6PfwDvi0K7lsS9Addzpb8o',
    appId: '1:252455385930:android:0281fdd70db3e954069fb3',
    messagingSenderId: '252455385930',
    projectId: 'registration-7d627',
    storageBucket: 'registration-7d627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB54ABaJI9Iqg-QfJEj32hFfOmg-Hz0v-I',
    appId: '1:252455385930:ios:a5fc9f2a98a6ab65069fb3',
    messagingSenderId: '252455385930',
    projectId: 'registration-7d627',
    storageBucket: 'registration-7d627.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB54ABaJI9Iqg-QfJEj32hFfOmg-Hz0v-I',
    appId: '1:252455385930:ios:a5fc9f2a98a6ab65069fb3',
    messagingSenderId: '252455385930',
    projectId: 'registration-7d627',
    storageBucket: 'registration-7d627.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLoT8km9AendlEHUHcqitr0qcewaL6qc',
    appId: '1:252455385930:web:332e8badf0047bcd069fb3',
    messagingSenderId: '252455385930',
    projectId: 'registration-7d627',
    authDomain: 'registration-7d627.firebaseapp.com',
    storageBucket: 'registration-7d627.firebasestorage.app',
    measurementId: 'G-BVLC0MXMLW',
  );
}
